---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность видеть на странице товара и в каталоге название, рейтинг, цену со скидкой и без нее
  - Пользователь должен иметь возможность добавлять товар в корзину и продолжать выбирать товары в каталоге
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен обрабатывать большое количество трафика
implicit:
  - Интерфейс сайта должен быть в умеренной цветовой гамме
  - Шрифт сайта должен быть понятным и корректным
